server:
  port: 8083
spring:
  application:
    name: seal-consumer
  cloud:
    consul:
      discovery:
        health-check-path: /actuator/health #检测实例健康
        health-check- interval: 10s
        #每隔1es检查
        hostname: 1.12.229.23
        #配置实例地址
        register: true # 自动注册
        service-name: ${spring.application.name} #实例名称
      host: 1.12.229.23
      port: 8500